NAME- Nitin kumar sharma ,
Email id - nitinsharma882000@gmail.com ,
mobile number - 9873147995

In [5]:
#ANSWER-1
import numpy as np
arr=np.arange(5, 50, 2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [13]:
#ANSWER -2
import numpy as np 
l = [] 
n = int(input("Enter number of elements : "))  
for i in range(0, n): 
	ele = int(input()) 
	l.append(ele) # adding the element 
print(l) 

s = [] 
n = int(input("Enter number of elements : "))  
for i in range(0, n): 
	ele = int(input()) 
	s.append(ele) # adding the element 
print(s) 

t=l+s
print ("Concatenated list using + : ",t)

Enter number of elements : 4
1
2
3
4
[1, 2, 3, 4]
Enter number of elements : 5
2
3
4
5
6
[2, 3, 4, 5, 6]
Concatenated list using + :  [1, 2, 3, 4, 2, 3, 4, 5, 6]


In [16]:
#ANSER -3
import numpy as np
a = np.array([[1,2],[1,2]])
a.ndim
a.shape
np.shape(a)
np.info(a)


In [23]:
#ANSWER -4
# create 1D numpy array from a list
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)



arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
#ANSWER -6
# taking an input list 
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
# taking an input list 
l1 = [] 
  
# taking an counter 
count = 0
  
# travesing the array 
for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item) 
  
# printing the output 
print("No of unique items are:", count) 

No of unique items are: 5
